Make the number of each backup type configurable (#31)
A value of 0 means to keep indefinitely.

diff --git a/acts b/acts
--- a/acts
+++ b/acts
@@ -97,6 +97,9 @@ postbackupscript="${postbackupscript=}"
 tarsnap="${tarsnap:=tarsnap}"
 tarsnapbackupoptions="${tarsnapbackupoptions=}"
 lockfile="${lockfile=/var/run/acts}"
+dailybackups="${dailybackups:=31}"
+monthlybackups="${monthlybackups:=12}"
+yearlybackups="${yearlybackups:=0}"
 LANG="${LANG=en_US.UTF-8}"
 export LANG
 
@@ -112,6 +115,10 @@ elif [ "$uselocaltime" = 1 ]; then
 else
     die "config-error message=\"invalid \$uselocaltime in acts.conf; valid options are 0 (for UTC) or 1 (for local time).\""
 fi
+
+[ $(( dailybackups )) = "$dailybackups" ]     || die "config-error message=\"Invalid \$dailybackups; must be a number.\""
+[ $(( monthlybackups )) = "$monthlybackups" ] || die "config-error message=\"Invalid \$monthlybackups; must be a number.\""
+[ $(( yearlybackups )) = "$yearlybackups" ]   || die "config-error message=\"Invalid \$yearlybackups; must be a number.\""
 
 # Create the lock. mkdir is atomic test/set, so use that instead of the typical test -f/touch combo
 if [ -d "$lockfile" ]; then
@@ -191,40 +198,36 @@ if [ "$backuprc" != "0" ]; then
     die "acts-tarsnap-error One of the backups failed -- not deleting old backups"
 fi
 
+prune_backups() {
+    backuplevel=$1 max=$2
+
+    if [ "$max" -gt 0 ]; then
+        backupslist=$(echo "$archives" | grep -E "$hostname-$backuplevel-.+-$nicedirname$" | sort -rn)
+        numberofbackups=$(echo "$backupslist" | awk 'END{print NR}')
+        if [ "$numberofbackups" -gt "$max" ]; then
+            log_debug "message=\"More than $max $backuplevel backups, deleting the oldest\""
+            echo "$backupslist" | tail -n +"$(( max+1 ))" | while read -r archiveprefixtodel; do
+                log_verbose "message=\"Deleting backup prefix $archiveprefixtodel*\""
+                echo "$archives" | grep -E "^$archiveprefixtodel" | while read -r archivetodel; do
+                    log_debug "message=\"Deleting backup $archivetodel\""
+                    $tarsnap -d -f "$archivetodel"
+                done
+            done
+        else
+            log_debug "message=\"Found $numberofbackups $backuplevel backups, not deleting\""
+        fi
+    else
+        log_debug "message=\"Keeping all $backuplevel backups indefinitely; not deleting any\""
+    fi
+}
+
 for dir in $backuptargets; do
     log_debug "message=\"Checking $dir for old backups to delete\""
     nicedirname=$(echo "$dir" | tr -d '/')
-    # We don't delete any yearly backups
 
-    # We keep 12 monthly backups
-    monthlybackups=$(echo "$archives" | grep "$hostname-monthly-.+-$nicedirname$" | sort -rn)
-    if [ "$(echo "$monthlybackups" | wc -l)" -gt 12 ]; then
-        log_debug 'message="More than 12 monthly backups, deleting the oldest"'
-        echo "$monthlybackups" | tail -n +13 | while read -r archiveprefixtodel; do
-            log_verbose "message=\"Deleting backup prefix $archiveprefixtodel*\""
-            echo "$archives" | grep -E "^$archiveprefixtodel" | while read -r archivetodel; do
-                log_debug "message=\"Deleting backup $archivetodel\""
-                $tarsnap -d -f "$archivetodel"
-            done
-        done
-    else
-        log_debug "message=\"Found $(echo "$monthlybackups" | wc -l) monthly backups, not deleting\""
-    fi
-
-    # We keep 31 daily backups
-    dailybackups=$(echo "$archives" | grep "$hostname-daily-.+-$nicedirname$" | sort -rn)
-    if [ "$(echo "$dailybackups" | wc -l)" -gt 31 ]; then
-        log_debug "message=\"More than 30 daily backups, deleting the oldest\""
-        echo "$dailybackups" | tail -n +32 | while read -r archiveprefixtodel; do
-            log_verbose "message=\"Deleting backup prefix $archiveprefixtodel*\""
-            echo "$archives" | grep -E "^$archiveprefixtodel" | while read -r archivetodel; do
-                log_debug "message=\"Deleting backup $archivetodel\""
-                $tarsnap -d -f "$archivetodel"
-            done
-        done
-    else
-        log_debug "message=\"Found $(echo "$dailybackups" | wc -l) daily backups, not deleting any\""
-    fi
+    prune_backups yearly  $yearlybackups
+    prune_backups monthly $monthlybackups
+    prune_backups daily   $dailybackups
 done
 
 # Run the post-backup script
