make acts /bin/sh compliant

diff --git a/acts b/acts
--- a/acts
+++ b/acts
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # One archive is created per day. The archive type is yearly, monthly or
 # daily.
@@ -41,11 +41,11 @@ log_debug() {
 }
 
 # When is now?
-today=$(date -u "+%Y-%m-%d_%H:%M:%S")
+today=`date -u "+%Y-%m-%d_%H:%M:%S"`
 # Instead of re-running date, be paranoid the day was microseconds away from ending
-year=$(echo $today | cut -d\_ -f1 | cut -d\- -f1)
-month=$(echo $today | cut -d\_ -f1 | cut -d\- -f2)
-day=$(echo $today | cut -d\_ -f1 | cut -d\- -f3)
+year=`echo $today | cut -d\_ -f1 | cut -d\- -f1`
+month=`echo $today | cut -d\_ -f1 | cut -d\- -f2`
+day=`echo $today | cut -d\_ -f1 | cut -d\- -f3`
 
 log_debug "It's $today"
 
@@ -77,10 +77,10 @@ if [ -n "$prebackupscript" ] ; then
 fi
 # Do the backup proper
 backuprc=0 # Notice any failed backups
-for dir in $(echo $backuptargets | tr ' ' '\n') ; do
+for dir in `echo $backuptargets | tr ' ' '\n'` ; do
 	log_verbose "Backing up "$dir"..."
-	nicedirname=$(echo $dir | tr -d '/')
-	$tarsnap -c -f "$hostname-$archivetype-$today-$nicedirname" -C / $dir || backuprc=$? # Since we mgiht run multiple tarsnaps, only overwrite backuprc if the exit code is != 0
+	nicedirname=`echo $dir | tr -d '/'`
+	$tarsnap -c -f "$hostname-$archivetype-$today-$nicedirname" -C / $dir || backuprc=$? # Since we might run multiple tarsnaps, only overwrite backuprc if the exit code is != 0
 done
 # Update the archive listing
 $tarsnap --list-archives > $archives
@@ -96,8 +96,8 @@ fi
 # We don't delete any yearly backups so ignore them
 
 # We keep 12 monthly backups
-monthlybackups=$(grep "$hostname-monthly-" $archives | sort -n | cut -d\_ -f1 | uniq)
-if [ $(echo "$monthlybackups" | wc -l) -gt 12 ] ; then
+monthlybackups=`grep "$hostname-monthly-" $archives | sort -n | cut -d\_ -f1 | uniq`
+if [ `echo "$monthlybackups" | wc -l` -gt 12 ] ; then
 	log_debug "More than 12 monthly backups, deleting the oldest"
 	echo "$monthlybackups" | head -n -12 | while read archiveprefixtodel ; do
 		log_verbose "Deleting monthly backup on $archiveprefixtodel"
@@ -109,8 +109,8 @@ if [ $(echo "$monthlybackups" | wc -l) -gt 12 ] ; then
 fi
 
 # We keep 30 daily backups
-dailybackups=$(grep "$hostname-daily-" $archives | sort -n | cut -d\_ -f1 | uniq)
-if [ $(echo "$dailybackups" | wc -l) -gt 30 ] ; then
+dailybackups=`grep "$hostname-daily-" $archives | sort -n | cut -d\_ -f1 | uniq`
+if [ `echo "$dailybackups" | wc -l` -gt 30 ] ; then
 	log_debug "More than 30 daily backups, deleting the oldest"
 	echo "$dailybackups" | head -n -30 | while read archiveprefixtodel ; do
 		log_verbose "Deleting $archiveprefixtodel"
